### ISSUE TITLE
[FEATURE] -- adding delete button to remove task notes etc

### ISSUE THREAD

**Issue by DEEP-666** [Polaris-School-of-Technology/Personal-Management-Dashboard#10]
--> A feature to delete tasks, notes, and goals should be implemented, such as adding a delete button for each item.

--> it has a feature that it will only delete the last added content only instead of deleting everyting in one 'click'.

https://github.com/user-attachments/assets/5b3a6403-cba5-4be5-9946-890956da31d8

Assign me this issue

**Comment by himkar-cmd** [comment]
Hi can you please assign this issue to me

**Comment by rahat2134** [comment]
Assigning this issue to @DEEP-666

**Comment by rahat2134** [comment]
It will be assigned to anyone else if seems inactive.

**Comment by rahat2134** [comment]
This issue has been solved by #70
