### ISSUE TITLE
Unavailability of Weather

### ISSUE THREAD

**Issue by Aryan-SINGH-GIT** [Polaris-School-of-Technology/Personal-Management-Dashboard#12]
![image](https://github.com/user-attachments/assets/c65a42da-dc43-4af7-837d-2a2a1a8eb6ef)
 
The website currently lacks a feature to display the weather information that I would like to add.

**Comment by rohansaini-02** [comment]
I wanted to update you on the project. I've added a weather box and a weather button to enhance our functionality. Now, users can easily access the weather information directly from the interface.
![Screenshot 2024-12-06 170129](https://github.com/user-attachments/assets/3e5b8abb-2c48-4869-bb78-1f67478a92e7)

**Comment by rahat2134** [comment]
In the weather section we want current weather with help of API
