### ISSUE TITLE
Adding current weather functionality

### ISSUE THREAD

**Issue by A9RYA6N** [Polaris-School-of-Technology/Personal-Management-Dashboard#15]
An API fetch needs to be added to make the "weather" part work

**Comment by KURO-1125** [comment]
There is a Section in the HTML and JavaScript for the Weather API integration.  I am creating this  as an issue , so please assign me this issue. 

I have integrated the Open Weather API to fetch and display weather data for a user-specified city under the Weather Section in the Code.

To solve this - 
Changes in HTML
1. I created a API key from the Open Weather API website .
2. Added City Input and a Get Weather Button in the HTML
3. Created a div in which the fetched data will be displayed.
![Screenshot 2024-12-07 123206](https://github.com/user-attachments/assets/a2991cfa-de63-457e-8f0f-b2efc7d99cc1)

Changes in CSS
1. Made the div element in which data will be displayed hidden initially.     
![Screenshot 2024-12-07 131808](https://github.com/user-attachments/assets/15414b7c-eb53-4fa9-88d6-638a8df9bf3e)


Changes in JavaScript
1.Added an Event Listener on the Get Weather Button so a function gets called that would fetch the data from the API and display the data.
2.The function fetchweather call the API and gets the data in JSON format
![image](https://github.com/user-attachments/assets/264bac5b-1478-48f4-9ada-cea7a9023447)
3. Used try and catch in case API  fails to get data to some other issue is there.
4. Then the required data like the Current temperature, Max temperature, Min temperature,  FeelsLike temperature, Humidity and Windspeed  are rounded off to the nearest Integer and are displayed on the HTML page .

JS CODE-
![image](https://github.com/user-attachments/assets/3624a10c-12d5-400f-8483-41b11cb2d28d)



Sample Screenshots - 
Input Box and Get Weather Button
![image](https://github.com/user-attachments/assets/a29f0d70-3e76-4319-9160-4a03221dbf2e)

Weather Being Displayed
![image](https://github.com/user-attachments/assets/c886c420-1b87-4915-9bd9-446356d7c13f)
![image](https://github.com/user-attachments/assets/c847bf4e-3bf9-4361-bb52-2a022891ce97)


If API call Fails
![image](https://github.com/user-attachments/assets/ea1d1669-2a72-4412-927d-74032f208ccf)


API CALL-
![image](https://github.com/user-attachments/assets/a9a11dce-7e6c-49b7-a9b9-f5820986e525)

API DATA-
![image](https://github.com/user-attachments/assets/f582391e-5435-40eb-8897-7265776c7980)


SAMPLE VIDEO-
https://github.com/user-attachments/assets/89b249bf-519e-4503-ae4a-a71ab5a96e99



@rahat2134   I hope my solution is satisfactory. Please assign this issue to me.

**Comment by rahat2134** [comment]
Assigning the issue to @KURO-1125 .

**Comment by KURO-1125** [comment]
> @KURO-1125 Are we getting current stats?

Yes, the stats displayed are real-time as they are fetched from Open-Weather API
