### ISSUE TITLE
Boring css style and home page design.

### ISSUE THREAD

**Issue by abhijit9040** [Polaris-School-of-Technology/Personal-Management-Dashboard#27]
changes in homepage style

**Comment by abhijit9040** [comment]
The changes include assigning unique IDs to buttons, adding placeholder adjustments, styling via CSS for a clean layout, and JavaScript for interactivity to manage tasks, notes, goals, and placeholder weather updates.
![Screenshot 2024-12-08 002833](https://github.com/user-attachments/assets/f4dac595-7e42-41ef-abd7-1bd3b58b45ad)
![Screenshot 2024-12-08 002932](https://github.com/user-attachments/assets/b0f6b7dd-f5e2-4723-b0ff-49eb2039fe70)
![Screenshot 2024-12-08 002947](https://github.com/user-attachments/assets/2940aece-b733-4981-a37b-30dcf9c3b906)

**Comment by rahat2134** [comment]
Not needed as of now. It more of a feature request with less priority.

**Comment by rahat2134** [comment]
This issue is not acceptable. Please read contributing guidelines.
