### ISSUE TITLE
Feature Request: Add DarkMode to the Dashboard.

### ISSUE THREAD

**Issue by SnehaChaursia** [Polaris-School-of-Technology/Personal-Management-Dashboard#39]
Description: Add a toogle button to switch  Dark and Light mode.

Benefits: Users nowdays like to work on dark mode to prevent eye strain,and adding these feature  will enhance the user experience and make the application more align with current UI/UX trends.
 

https://github.com/user-attachments/assets/6be0df17-6df5-4d38-adc9-daf645f244c6

My Approach:
![Screenshot 2024-12-13 185016](https://github.com/user-attachments/assets/6eee062c-8105-4e08-a578-984ee7425530)
![Screenshot 2024-12-13 185051](https://github.com/user-attachments/assets/dea8dbba-6f02-41fa-aff6-da013301b453)
@Rahat-CP @rahat2134 I would like to work on this feature. Please  review and assign me!

**Comment by Rahat-CP** [comment]
Looks good, assigning you the issue.
