### ISSUE TITLE
[FEATURE] Focus-timer section helpful to complete task with  a little break

### ISSUE THREAD

**Issue by ROHITKUMARMODI** [Polaris-School-of-Technology/Personal-Management-Dashboard#65]
🕒 Focus Timer Feature
Introduced a Focus Timer to enhance productivity by implementing a Pomodoro-style time management tool. This feature allows users to focus on tasks with a set 25-minute timer.

Key Features:

25-Minute Timer: A default timer duration for focused work sessions.
Start Button: Starts the 25-minute countdown.
Reset Button: Resets the timer back to the 25-minute default value at any point.
This feature provides an intuitive way to track focused work intervals and manage productivity effectively.

with focus timer

and here is its code 
**#html**

 ![image](https://github.com/user-attachments/assets/f17ee4e7-878d-488e-80a8-743f316a1b73)

#**css**

![image](https://github.com/user-attachments/assets/172e0090-43b1-4837-9727-b2080eabee7b)

# **js**

![image](https://github.com/user-attachments/assets/e4c78415-aae7-4729-908c-62d21e07a4c1)

this is the code which i added .

Uploading Screen Recording 2024-12-13 164258.mp4…

***please @rahat2134  assign me this issue on this project***

**Comment by ROHITKUMARMODI** [comment]
i hope this feature will make me to assign this issue

**Comment by rahat2134** [comment]
Try to be consistent with the overall website. Read the guidelines in github discussion.
Don't change the color etc.

**Comment by ROHITKUMARMODI** [comment]
Ok bhaiya thankyou

**Comment by ROHITKUMARMODI** [comment]
issue idea to solve

**Comment by ROHITKUMARMODI** [comment]
issue solved

**Comment by rahat2134** [comment]
![image](https://github.com/user-attachments/assets/1c09f375-55ae-4855-a596-27caa43fceea)
