### ISSUE TITLE
Feature Integration : Added Edit and Delete button .

### ISSUE THREAD

**Issue by SnehaChaursia** [Polaris-School-of-Technology/Personal-Management-Dashboard#67]
Description : Add a EDIT BUTTON to edit the data  and also a DELETE BUTTON  to delete specific task , goal or note.

https://github.com/user-attachments/assets/174655b0-66f7-4e71-942c-528b5f1214ec

Approach: Introduces two function one for deleting  and one for editing the content.
![Screenshot 2024-12-10 130358](https://github.com/user-attachments/assets/240d7bf4-37d5-4809-b32b-fae0cd01bceb)

Dynamically added buttons in the newTask content,similarlly for note and goal section also.
![Screenshot 2024-12-10 125528](https://github.com/user-attachments/assets/5061eb4a-86d5-4111-9416-09906166335f)

@rahat2134 I would like to work on this issue please assign me!

**Comment by rahat2134** [comment]
Solution seems good. Assigning you the issue, Please co-ordinate with #10  assigne to come across a good solution such that there will not be any merge conflict in the future btw you  both.

**Comment by SnehaChaursia** [comment]
okay ! i will take of that.
