### ISSUE TITLE
[Feature] Add Password Visibility Toggle Feature 👁️

### ISSUE THREAD

**Issue by oathar** [Polaris-School-of-Technology/Personal-Management-Dashboard#71]
### Add a password visibility toggle to the password input field. This will allow users to click an eye icon to show or hide the password they are typing. This will improve user experience and privacy while typing passwords.

*How I Implemented this feature:*
**Details:**
- Added an eye icon next to the password field. (FontAwesome icons) 
![image](https://github.com/user-attachments/assets/4c3718e2-63dc-450c-9d7a-68f2421e7ebc)

- When the icon is clicked, the password will toggle between visible and hidden.
Initially Hidden:
![image](https://github.com/user-attachments/assets/4b74f313-9b15-4c81-9fbd-c6db8e0f9936)
After clicking the eye icon:
![image](https://github.com/user-attachments/assets/31f4bed3-45f8-42cb-98f7-2dff976ee9a6)

- Used FontAwesome icons (eye and eye-slash) for the toggle button.
 `  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">`

HTML:
![image](https://github.com/user-attachments/assets/cdceb1aa-23f7-4e8a-9109-d145dde124f2)
JS: 
![image](https://github.com/user-attachments/assets/cc5ee26d-44d5-4908-99de-ecfdb699da77)

Video Demo:
https://github.com/user-attachments/assets/cc40f83d-f372-424e-b147-84db064e7c7b

@rahat2134 , could you please assign me the "Password Visibility Toggle" feature issue? I am eager to work on it and contribute to the project. Thank you!

**Comment by mahendra-918** [comment]
@rahat2134 can you please assign to me

**Comment by Rahat-CP** [comment]
Add Password Visibility Toggle Feature 👁️  ----> [Feature] Add Password Visibility Toggle Feature 👁️

**Comment by Rahat-CP** [comment]
Assigning you the issue.
