### ISSUE TITLE
[Feature Added] :Implement Dark Mode for Personal Management Dashboard

### ISSUE THREAD

**Issue by Aryan-SINGH-GIT** [Polaris-School-of-Technology/Personal-Management-Dashboard#87]
### Issue:
This issue involves implementing a dark mode feature for the personal management dashboard. The goal was to provide users with an option to toggle between light and dark themes, enhancing usability in low-light environments and offering a visually appealing alternative.

### Solution:
The dark mode was implemented by adding a toggle button that switches the color scheme of the dashboard. The following changes were made:

### HTML Changes:

Added a button to toggle dark mode:

### JavaScript Changes:

Created a function to toggle dark mode. This function changes the background and text colors of various elements:
![Screenshot 2024-12-16 120000](https://github.com/user-attachments/assets/c5a13c80-36cb-4293-8666-1c252831e057)

### Steps to Enable Dark Mode

- Open the personal management dashboard.
- Click on the "Enable Dark mode" button.
 
![Screenshot 2024-12-16 120142](https://github.com/user-attachments/assets/17888cd0-9694-4376-86f1-dec233246109)

- Observe the changes in the color scheme of the dashboard.

![Screenshot 2024-12-16 120127](https://github.com/user-attachments/assets/ace0f2c7-e9b9-4379-98b5-cd9a0986f9cd)

**Comment by rahat2134** [comment]
duplicate...
